[env:rover]
platform = atmelsam
board = adafruit_metro_m0
framework = arduino

build_src_filter = +<rover/>

monitor_speed = 115200

upload_port = COM3
upload_protocol = sam-ba

lib_deps =
  arduino-libraries/WiFi101

[env:controller]
platform = atmelsam
board = adafruit_metro_m0
framework = arduino

build_src_filter = +<controller/>

monitor_speed = 115200

upload_port = COM5
upload_protocol = sam-ba

lib_deps =
  arduino-libraries/WiFi101