[env:adafruit_metro_m0express]
platform = atmelsam
board = adafruit_metro_m0
framework = arduino

monitor_speed = 115200
upload_protocol = sam-ba

lib_deps =
  arduino-libraries/WiFi101
  khoih-prog/WiFiWebServer